// Genesis : The World Creation
#pragma once

#include "NativeGameplayTags.h"

namespace FMoonveilGameplayTags
{
	// Input Tags //
#pragma region InputTag
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_Sword);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip_Sword);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Light_Sword);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Heavy_Sword);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchTarget);

	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_OnPressed);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_OnPressed_Block);

	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_LockOnOff);
#pragma endregion

	// Player Tags //
#pragma region PlayerTag
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword);

	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Sword);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Sword);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Sword);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Sword);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Rolling);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_LockOnOff);

	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rolling);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Locking);

	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_HitReact_Front);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_HitReact_Back);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_HitReact_Left);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_HitReact_Right);

	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_Attack_Light);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_Attack_Heavy);

	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_TargetSwitch_ToAttacker);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_TargetSwitch_Left);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_TargetSwitch_Right);
#pragma endregion

	// Enemy Tags //
#pragma region EnemyTag
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);

	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack);
#pragma endregion

	// Event Tags //
#pragma region EventTag
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Equip_Sword);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Unequip_Sword);
		
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_Melee);

	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Block_Successed);

	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Hit_Melee);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Hit_React);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Hit_Pause);

	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Status_Death);
#pragma endregion

	// Shared Tags //
#pragma region SharedTag
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReaction);
	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	MOONVEIL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);
#pragma endregion

}